name: API Automated Quality Gate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  api-test-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install Dependencies
        run: |
          npm install
          npm install -g newman

      - name: Start Mock Server (Background)
        run: |
          npm start &
          echo "Server spinning up in background process..."

      - name: Wait for Server to be Ready
        run: |
          echo "Waiting for localhost:3000 to wake up..."
          npx wait-on http://localhost:3000 --timeout 30000

      - name: Run Newman API Automation Suite
        run: |
          npx newman run crud_collection.json -e local_env.json -r cli,htmlextra

      - name: Archive QA Automation Report
        uses: actions/upload-artifact@v4
        with:
          name: api-qa-dashboard-report
          path: newman/
          retention-days: 14